# -*- coding: utf-8 -*-
"""extraction_ind_veg_gee.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1udznT2VlpHGvXOFMKrklNCulQZzqDA1f
"""

// Máscara de nuvens usando a banda SCL do Sentinel-2 SR
function maskS2cloudsSR(image) {
  var scl = image.select('SCL');
  var mask = scl.neq(3).and(scl.neq(8)).and(scl.neq(9)).and(scl.neq(10));
  return image.updateMask(mask);
}

// Funções índices
function addNDVI(image) {
  return image.addBands(image.normalizedDifference(['B8', 'B4']).rename('NDVI'));
}
function addEVI(image) {
  var evi = image.expression(
    '2.5 * ((NIR - RED) / (NIR + 6 * RED - 7.5 * BLUE + 1))', {
      'NIR': image.select('B8'),
      'RED': image.select('B4'),
      'BLUE': image.select('B2')
    });
  var eviClamped = evi.clamp(-1, 1).rename('EVI');
  return image.addBands(eviClamped);
}
function addFC(image) {
  return image.addBands(image.select('NDVI').multiply(100).rename('FC'));
}

// Lista das regiões
var regions = {



};

var dem = ee.Image('USGS/SRTMGL1_003').rename('DEM');

var startDate = ee.Date('2024-01-01');
var endDate = ee.Date('2025-05-30');
var months = ee.List.sequence(0, endDate.difference(startDate, 'month').subtract(1));

var allRegionsFeatures = [];

// Função principal de processamento por região
function processRegion(regionName, regionGeom) {

  var collection = ee.ImageCollection('COPERNICUS/S2_SR')
    .filterBounds(regionGeom)
    .filterDate(startDate, endDate)
    .map(maskS2cloudsSR)
    .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20))
    .map(addNDVI)
    .map(addEVI)
    .map(addFC);

  var monthlyFeatures = months.map(function(monthOffset) {
    var start = startDate.advance(monthOffset, 'month');
    var end = start.advance(1, 'month');
    var monthlyCol = collection.filterDate(start, end);

    return ee.Algorithms.If(
      monthlyCol.size().gt(0),
      ee.Feature(null, {
        'date': start.format('YYYY-MM'),
        'region': regionName,
        'NDVI': monthlyCol.select('NDVI').mean().reduceRegion({
          reducer: ee.Reducer.mean(),
          geometry: regionGeom,
          scale: 10,
          maxPixels: 1e13
        }).get('NDVI'),
        'EVI': monthlyCol.select('EVI').mean().reduceRegion({
          reducer: ee.Reducer.mean(),
          geometry: regionGeom,
          scale: 10,
          maxPixels: 1e13
        }).get('EVI'),
        'DEM': dem.reduceRegion({
          reducer: ee.Reducer.mean(),
          geometry: regionGeom,
          scale: 30,
          maxPixels: 1e13
        }).get('DEM')
      }),
      null
    );
  });

  return ee.FeatureCollection(monthlyFeatures).filter(ee.Filter.notNull(['date']));
}

// Processa todas as regiões
for (var key in regions) {
  var regionFC = processRegion(key, regions[key]);
  allRegionsFeatures.push(regionFC);
}

// Combina todas as FeatureCollections
var mergedCollection = ee.FeatureCollection(allRegionsFeatures).flatten();

// Exporta único CSV
Export.table.toDrive({
  collection: mergedCollection,
  description: 'COPERNICUS/S2_SR_ind_veg',
  fileFormat: 'CSV'
});